import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Mohanraj Profile',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`antialiased h-full bg-gradient-to-tr from-indigo-600 via-purple-800 to-pink-900 `}
      >
        {children}
      </body>
    </html>
  )
}
