name: Caching Dependencies
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: using custom actions for cache job
        id: cache-results
        uses: ./.github/actions/cached-deps
        with:
          should-cache: 'true'
      - name: Output information
        run: echo "Cache used? ${{ steps.cache-results.outputs.used-cache }}"
      # following below is manual steps
      # - name: Cache Dependencies
      #   uses: actions/cache@v3
      #   id: cache-id
      #   with:
      #     path: ~/.npm
      #     key: deps-node-modules${{ hashFiles('**/package-lock.json') }}
      # - name: Install Dependencies
      #   if: steps.cache-id.outputs.cache-hit != 'true'
      #   run: npm ci
