name: Conditional Jobs
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        id: install-deps
        run: npm install
      - name: Generate Report
        if: failure() && steps.install-deps.outcome == 'failure'
        run: echo 'Installation issues report generated.'
    report:
      runs-on: ubuntu-latest
      needs: [deploy]
      if: failure()
      steps:
        - name: Copy reports
        run: echo 'reports copied'
        