name: Event Filters
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - master
      - main
  push:
    branches:
      - 'dev-*' # can be any branch which is `dev-` prefixed
      - 'feature/**' # can be any branch which is comes under feature group
    paths-ignore:
      - '.github/workflows/*' # skipping the workflow for this files changes (push operation)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Log
        run: echo 'test run'
