name: Hello World
on:
  workflow_dispatch: # Manual trigger
  push: # Trigger on push
    branches:
      - main # Change this to your default branch if different
  pull_request: # Trigger on pull requests
    branches:
      - main # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "Hello World!"

      - name: Print Goodbye
        run: echo "Goodbye! Have a nice day"
