name: Multiple Events
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: pnpm install
