name: Multiple Jobs
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 6.10.0
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
  test:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Cases
        run: pnpm test
