name: Artifacts
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish-id.outputs.custom-name }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pnpm install
      - name: Build Site
        run: pnpm build
      - name: Publish JS Filename
        id: publish-id
        run: find dist/assets/*.js -type f -execdir echo 'custom-name={}' >> $GITHUB_OUPUT ';'

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
        #   for multiple files
        #   path: |
        #     dist
        #     package.json
